sudo: required
language: ruby
services:
- docker
before_install:
- docker -H tcp://9.45.202.237:4243 build -t mysql_5.1.73_centos66_jpetstore ./JPetStore_DB/Dockerfile

script:
- bundle exec rake test
